const { Pool } = require('pg');
const bcrypt = require('bcryptjs');
require('dotenv').config({ path: require('path').join(__dirname, '../../../.env') });

const pool = new Pool({
  host: process.env.DB_HOST || 'localhost',
  port: parseInt(process.env.DB_PORT || '5432'),
  database: process.env.DB_NAME || 'pharma_docs',
  user: process.env.DB_USER || 'postgres',
  password: process.env.DB_PASSWORD || 'postgres',
});

async function seed() {
  console.log('🔧 Setting up database schema...');

  await pool.query(`
    DROP TABLE IF EXISTS documents CASCADE;
    DROP TABLE IF EXISTS users CASCADE;

    CREATE TABLE users (
      id SERIAL PRIMARY KEY,
      name VARCHAR(255) NOT NULL,
      email VARCHAR(255) UNIQUE NOT NULL,
      password_hash VARCHAR(255) NOT NULL,
      role VARCHAR(50) DEFAULT 'analyst',
      created_at TIMESTAMP DEFAULT NOW()
    );

    CREATE TABLE documents (
      id SERIAL PRIMARY KEY,
      title VARCHAR(500) NOT NULL,
      description TEXT,
      category VARCHAR(100) NOT NULL,
      status VARCHAR(50) DEFAULT 'draft',
      priority VARCHAR(20) DEFAULT 'medium',
      metadata JSONB DEFAULT '{}',
      created_by VARCHAR(255),
      created_at TIMESTAMP DEFAULT NOW(),
      updated_at TIMESTAMP DEFAULT NOW()
    );

    CREATE INDEX idx_documents_category ON documents(category);
    CREATE INDEX idx_documents_status ON documents(status);
  `);

  console.log('👤 Creating users...');
  const hash = await bcrypt.hash('password123', 10);
  await pool.query(
    `INSERT INTO users (name, email, password_hash, role) VALUES
     ('Dr. Sarah Johnson', 'admin@pharma.com', $1, 'admin'),
     ('Dr. Michael Chen', 'analyst@pharma.com', $1, 'analyst'),
     ('Dr. Emily Davis', 'reviewer@pharma.com', $1, 'reviewer')`,
    [hash]
  );

  console.log('📄 Seeding documents...');

  const categories = {
    lab_results: [
      { title: 'Blood Panel Analysis - Batch TR-2024-001', description: 'Complete blood count and metabolic panel results for Phase III trial participants. Hemoglobin levels range 12.1-16.3 g/dL, WBC counts within normal limits. ALT/AST liver enzymes show slight elevation in 3 subjects requiring follow-up.', status: 'completed', priority: 'high', metadata: { test_type: 'Blood Panel', sample_count: 150, lab: 'Central Analytics Lab', batch: 'TR-2024-001' } },
      { title: 'Urinalysis Results - Study PH-445', description: 'Routine urinalysis for ongoing Phase II study participants. Specific gravity 1.005-1.030, pH range 5.0-8.0. Two anomalous protein levels detected in cohort B requiring retest.', status: 'review', priority: 'medium', metadata: { test_type: 'Urinalysis', sample_count: 85, lab: 'BioTest Laboratories' } },
      { title: 'Microbiological Assay - Raw Material RM-7892', description: 'Microbial limit testing of incoming raw materials. Total aerobic count < 100 CFU/g, total yeast and mold < 10 CFU/g. All results within specification. No pathogens detected.', status: 'approved', priority: 'medium', metadata: { test_type: 'Microbiology', material: 'Active Pharmaceutical Ingredient', spec: 'USP <61>' } },
      { title: 'HPLC Purity Analysis - Compound XR-29', description: 'High-performance liquid chromatography analysis of drug substance purity. Main peak area 99.7%, largest impurity 0.12%. Meets ICH Q3A guidelines for impurity limits.', status: 'completed', priority: 'high', metadata: { test_type: 'HPLC', purity: '99.7%', method: 'USP Monograph', instrument: 'Agilent 1260' } },
      { title: 'Dissolution Testing - Tablet Batch BT-5543', description: 'In vitro dissolution rate testing for 100mg tablet formulation. All 12 units meet Q+5% at 30 minutes. Mean dissolution 95.2% at 45 minutes in 0.1N HCl.', status: 'approved', priority: 'low', metadata: { test_type: 'Dissolution', dosage_form: 'Tablet 100mg', apparatus: 'USP Apparatus II' } },
      { title: 'Stability Study - 6 Month Accelerated', description: 'Accelerated stability data at 40°C/75% RH for formulation F-2024. Assay remains 98.1% at 6 months. Degradation products below 0.5%. Package integrity maintained.', status: 'completed', priority: 'high', metadata: { test_type: 'Stability', condition: '40°C/75% RH', duration: '6 months', storage: 'HDPE bottle' } },
      { title: 'Endotoxin Testing - Injectable Batch IB-901', description: 'Bacterial endotoxin testing using LAL kinetic turbidimetric method. All samples < 0.25 EU/mL against limit of 5 EU/mL. Batch passes specification.', status: 'approved', priority: 'high', metadata: { test_type: 'Endotoxin', method: 'LAL Kinetic Turbidimetric', limit: '5 EU/mL' } },
      { title: 'Particle Size Distribution - API Lot L-3321', description: 'Laser diffraction analysis of API particle size. D10: 2.1μm, D50: 15.3μm, D90: 45.7μm. Distribution within specification for tablet compression.', status: 'completed', priority: 'medium', metadata: { test_type: 'Particle Size', method: 'Laser Diffraction', instrument: 'Malvern Mastersizer' } },
      { title: 'Residual Solvent Analysis - GC Headspace', description: 'Gas chromatography headspace analysis for residual solvents in API. Methanol < 500 ppm (limit 3000 ppm), Acetone < 100 ppm (limit 5000 ppm). ICH Q3C compliant.', status: 'approved', priority: 'medium', metadata: { test_type: 'Residual Solvents', method: 'GC Headspace', guideline: 'ICH Q3C' } },
      { title: 'Heavy Metals Screening - Excipient Batch EB-112', description: 'ICP-MS analysis for elemental impurities per ICH Q3D. Lead < 0.1 ppm, Arsenic < 0.05 ppm, Cadmium < 0.02 ppm. All within permitted daily exposure limits.', status: 'completed', priority: 'high', metadata: { test_type: 'Heavy Metals', method: 'ICP-MS', guideline: 'ICH Q3D' } },
      { title: 'Water Activity Testing - Powder Blend PB-667', description: 'Water activity measurement of granulated powder blend. Aw = 0.32 at 25°C, well below critical threshold of 0.60. Suitable for encapsulation.', status: 'approved', priority: 'low', metadata: { test_type: 'Water Activity', result: '0.32 Aw', limit: '< 0.60 Aw' } },
      { title: 'Sterility Testing - Ophthalmic Solution OS-44', description: 'Membrane filtration sterility test per USP <71>. No growth observed in FTM or SCDM after 14-day incubation. Batch meets sterility requirements.', status: 'approved', priority: 'high', metadata: { test_type: 'Sterility', method: 'Membrane Filtration', incubation: '14 days' } },
      { title: 'Karl Fischer Moisture - Capsule Fill CF-221', description: 'Coulometric Karl Fischer titration for moisture content. Result: 2.3% w/w against specification of NMT 4.0%. Acceptable for long-term stability.', status: 'completed', priority: 'medium', metadata: { test_type: 'Moisture Content', method: 'Karl Fischer Coulometric', result: '2.3%' } },
      { title: 'Bioburden Assessment - Clean Room Monitoring', description: 'Environmental monitoring of Grade A clean room. Settle plates: 0 CFU/4hr, Active air: < 1 CFU/m³. All contact plates negative. Room classification maintained.', status: 'approved', priority: 'high', metadata: { test_type: 'Bioburden', area: 'Grade A Clean Room', frequency: 'Weekly' } },
      { title: 'Potency Assay - Biologic Drug BIO-78', description: 'Cell-based potency assay for monoclonal antibody product. Relative potency 102% (specification 80-125%). Dose-response curve R² = 0.998. Assay valid per system suitability.', status: 'review', priority: 'high', metadata: { test_type: 'Potency', method: 'Cell-Based Assay', result: '102% relative potency' } },
    ],
    fda_compliance: [
      { title: 'FDA 21 CFR Part 211 - cGMP Compliance Audit', description: 'Annual comprehensive audit of current Good Manufacturing Practice compliance. Covers personnel qualifications, building/facilities, equipment, production controls, lab controls, and records/reports. Three minor observations noted.', status: 'review', priority: 'high', metadata: { regulation: '21 CFR 211', audit_type: 'Annual', findings: 3, classification: 'Satisfactory' } },
      { title: 'FDA Form 483 Response - Inspection INS-2024-03', description: 'Formal response to FDA Form 483 observations from March 2024 inspection. Addresses observations regarding equipment cleaning validation, batch record documentation, and environmental monitoring frequency.', status: 'in_progress', priority: 'critical', metadata: { form: 'FDA 483', observations: 3, deadline: '2024-04-15', inspector: 'J. Martinez' } },
      { title: 'Annual Product Review - APR-2024 Metformin 500mg', description: 'Comprehensive annual product review covering all batches manufactured in 2024. Includes trend analysis of critical quality attributes, stability data review, complaints, deviations, and CAPA effectiveness.', status: 'completed', priority: 'high', metadata: { product: 'Metformin 500mg', batches_reviewed: 24, period: 'Jan-Dec 2024' } },
      { title: 'Drug Master File Update - DMF Type II', description: 'Update to Drug Master File for active pharmaceutical ingredient manufacturing process change. Includes updated flow diagrams, equipment specifications, and in-process controls.', status: 'draft', priority: 'high', metadata: { dmf_type: 'Type II', substance: 'API-2947', change_type: 'Manufacturing Process' } },
      { title: 'REMS Assessment Report - Q4 2024', description: 'Risk Evaluation and Mitigation Strategy assessment for restricted distribution program. Patient enrollment tracking, prescriber certification status, and adverse event monitoring metrics reviewed.', status: 'completed', priority: 'high', metadata: { program: 'REMS', quarter: 'Q4 2024', enrolled_patients: 2340 } },
      { title: 'FDA Pre-Approval Inspection Readiness', description: 'Pre-approval inspection preparation checklist and gap assessment for NDA submission. Covers data integrity, equipment qualification, method validation, and batch record review readiness.', status: 'in_progress', priority: 'critical', metadata: { nda_number: 'NDA-215847', target_date: '2024-06-01' } },
      { title: 'Adverse Event Reporting - MedWatch 3500A', description: 'Compilation of serious adverse event reports for quarterly FDA submission. 12 SAEs reported, 3 classified as unexpected. Causality assessments and follow-up documentation included.', status: 'review', priority: 'critical', metadata: { report_type: 'MedWatch 3500A', period: 'Q1 2024', total_saes: 12 } },
      { title: 'Electronic Records Compliance - 21 CFR Part 11', description: 'Assessment of electronic records and signatures compliance. Covers system validation, audit trails, electronic signatures, and access controls across LIMS, ERP, and document management systems.', status: 'completed', priority: 'high', metadata: { regulation: '21 CFR Part 11', systems_assessed: 5 } },
      { title: 'Label Compliance Review - OTC Product Line', description: 'Review of OTC drug product labeling compliance with FDA requirements. Drug Facts panel accuracy, active ingredient listings, adequate directions for use, and required warnings verified.', status: 'approved', priority: 'medium', metadata: { product_line: 'OTC Analgesics', products_reviewed: 8 } },
      { title: 'GLP Compliance - Nonclinical Study NS-445', description: 'Good Laboratory Practice compliance documentation for pivotal nonclinical toxicology study. Protocol adherence, raw data integrity, specimen accountability, and final report accuracy verified.', status: 'completed', priority: 'high', metadata: { regulation: '21 CFR Part 58', study: 'NS-445', species: 'Rat/Dog' } },
      { title: 'Post-Market Surveillance Report - Year 3', description: 'Annual post-market surveillance report documenting product performance, complaint trends, adverse events, and field actions. Overall safety profile consistent with approved labeling.', status: 'review', priority: 'high', metadata: { product: 'CardioGuard XR', year: 3, complaints: 47 } },
      { title: 'FDA Warning Letter Response Plan', description: 'Strategic response plan for FDA warning letter regarding data integrity findings. Includes root cause analysis, immediate corrective actions, and long-term preventive measures with timeline.', status: 'in_progress', priority: 'critical', metadata: { letter_date: '2024-02-15', response_deadline: '2024-03-15' } },
      { title: 'Prescription Drug User Fee Act (PDUFA) Filing', description: 'PDUFA date tracking and submission documentation for pending NDA. User fee payment confirmation, pre-submission meeting minutes, and filing checklist completed.', status: 'completed', priority: 'high', metadata: { pdufa_date: '2024-09-30', fee_amount: '$3,242,026' } },
      { title: 'Combination Product Compliance - 21 CFR 4', description: 'Regulatory assessment for drug-device combination product. Determination of primary mode of action, applicable CGMP requirements, and post-market reporting obligations documented.', status: 'draft', priority: 'medium', metadata: { product_type: 'Drug-Device Combination', regulation: '21 CFR Part 4' } },
      { title: 'Import/Export Compliance Documentation', description: 'FDA import compliance documentation for API sourced from overseas manufacturer. Drug Listing, Establishment Registration, and Prior Notice filings verified current.', status: 'approved', priority: 'medium', metadata: { origin_country: 'India', product: 'API-Ibuprofen', registration: 'Current' } },
    ],
    drug_trials: [
      { title: 'Phase III Clinical Trial - CardioGuard XR', description: 'Randomized, double-blind, placebo-controlled trial for novel anticoagulant. 2,400 subjects enrolled across 45 sites. Primary endpoint: reduction in major cardiovascular events at 12 months.', status: 'in_progress', priority: 'critical', metadata: { phase: 'III', subjects: 2400, sites: 45, indication: 'Cardiovascular', protocol: 'CG-301' } },
      { title: 'Phase II Dose-Finding - NeuroClear 50/100/200mg', description: 'Adaptive dose-finding study for Alzheimer\'s disease treatment. Three dose arms plus placebo. Bayesian adaptive design allows interim analysis-driven dose selection.', status: 'in_progress', priority: 'high', metadata: { phase: 'II', subjects: 360, doses: '50/100/200mg', indication: 'Alzheimer\'s Disease' } },
      { title: 'Phase I First-in-Human - Compound ARX-7', description: 'Single ascending dose study in healthy volunteers. Starting dose 5mg with sentinel dosing. Safety, tolerability, PK, and preliminary PD assessments through 72-hour observation.', status: 'completed', priority: 'high', metadata: { phase: 'I', subjects: 48, design: 'SAD', compound: 'ARX-7' } },
      { title: 'Bioequivalence Study - Generic Atorvastatin 40mg', description: 'Two-way crossover bioequivalence study comparing generic formulation to reference listed drug. 36 healthy volunteers under fasting conditions. PK parameters Cmax and AUC within 80-125%.', status: 'completed', priority: 'medium', metadata: { type: 'Bioequivalence', subjects: 36, design: 'Crossover', drug: 'Atorvastatin 40mg' } },
      { title: 'Phase IIb Efficacy - OncoBlock Immunotherapy', description: 'Open-label efficacy trial for PD-L1 checkpoint inhibitor in advanced NSCLC. Primary endpoint: objective response rate per RECIST 1.1. Secondary endpoints include PFS, OS, and duration of response.', status: 'in_progress', priority: 'critical', metadata: { phase: 'IIb', subjects: 180, indication: 'NSCLC', endpoint: 'ORR' } },
      { title: 'Pediatric Extension Study - AllerFree Syrup', description: 'Open-label safety and PK study in pediatric population ages 2-11. Weight-based dosing regimen. Special considerations for palatability and compliance assessment.', status: 'review', priority: 'high', metadata: { phase: 'III', subjects: 120, population: 'Pediatric 2-11yr', formulation: 'Oral Syrup' } },
      { title: 'Long-Term Safety Extension - DiabControl', description: '5-year open-label extension study for Type 2 diabetes treatment. Monitoring long-term cardiovascular outcomes, renal function, and glycemic durability. Annual interim safety reports.', status: 'in_progress', priority: 'high', metadata: { duration: '5 years', subjects: 890, indication: 'Type 2 Diabetes' } },
      { title: 'Adaptive Platform Trial - COVID Therapeutics', description: 'Master protocol platform trial testing multiple therapeutic agents. Bayesian response-adaptive randomization. Currently evaluating 3 active arms with potential for arm additions.', status: 'in_progress', priority: 'critical', metadata: { design: 'Platform Trial', active_arms: 3, sites: 28 } },
      { title: 'Phase III Pivotal - RheumaRelief Biologic', description: 'Pivotal efficacy and safety trial for anti-TNF biologic in rheumatoid arthritis. ACR20/50/70 response rates at week 24. Includes radiographic progression substudy.', status: 'review', priority: 'high', metadata: { phase: 'III', subjects: 650, indication: 'Rheumatoid Arthritis', duration: '52 weeks' } },
      { title: 'Drug-Drug Interaction Study - HepatoShield', description: 'Clinical DDI study evaluating pharmacokinetic interactions with CYP3A4 and CYP2D6 substrates. Crossover design with probe substrates midazolam and dextromethorphan.', status: 'completed', priority: 'medium', metadata: { type: 'DDI', subjects: 24, enzymes: 'CYP3A4/CYP2D6' } },
      { title: 'Real-World Evidence Study - PainEase XR', description: 'Prospective observational study collecting real-world effectiveness and safety data. 5,000 patients across community practices. Electronic health record data linkage.', status: 'in_progress', priority: 'medium', metadata: { type: 'RWE', subjects: 5000, duration: '24 months' } },
      { title: 'Vaccine Efficacy Trial - FluShield Quadrivalent', description: 'Randomized controlled trial for next-generation influenza vaccine. 15,000 subjects across Northern and Southern hemisphere sites. Primary endpoint: laboratory-confirmed influenza.', status: 'in_progress', priority: 'critical', metadata: { phase: 'III', subjects: 15000, sites: 120, type: 'Vaccine' } },
      { title: 'Thorough QT/QTc Study - Compound BX-42', description: 'ICH E14 compliant thorough QT study with positive control (moxifloxacin). Concentration-QTc modeling approach. 60 healthy volunteers in 4-period crossover.', status: 'completed', priority: 'high', metadata: { type: 'TQT', subjects: 60, design: '4-period crossover', guideline: 'ICH E14' } },
      { title: 'Compassionate Use Program - EmergeTx', description: 'Expanded access program for life-threatening condition with no approved treatments. Individual patient IND submissions. Safety monitoring and reporting per FDA requirements.', status: 'in_progress', priority: 'critical', metadata: { type: 'Expanded Access', patients: 34, status: 'Enrolling' } },
      { title: 'Phase I/II Basket Trial - Precision Oncology', description: 'Tumor-agnostic basket trial for targeted therapy based on specific genetic mutations. Multiple tumor types enrolled under single protocol. Bayesian hierarchical modeling for efficacy.', status: 'in_progress', priority: 'high', metadata: { phase: 'I/II', design: 'Basket Trial', tumor_types: 8, biomarker: 'FGFR2 Fusion' } },
    ],
    regulatory_submissions: [
      { title: 'NDA Submission - CardioGuard XR Tablets', description: 'New Drug Application for novel oral anticoagulant. Complete Module 1-5 CTD format submission including quality, nonclinical, and clinical data packages. PDUFA goal date Q3 2024.', status: 'submitted', priority: 'critical', metadata: { type: 'NDA', number: 'NDA-215847', format: 'eCTD', modules: '1-5' } },
      { title: 'ANDA Filing - Generic Metformin ER 750mg', description: 'Abbreviated New Drug Application for extended-release formulation. Bioequivalence data, pharmaceutical equivalence documentation, and DMF reference authorization included.', status: 'review', priority: 'high', metadata: { type: 'ANDA', reference_drug: 'Glucophage XR', formulation: 'ER Tablet' } },
      { title: 'IND Application - Compound ARX-7', description: 'Investigational New Drug application for first-in-human study. Includes CMC data, pharmacology/toxicology summaries, clinical protocol, and investigator brochure.', status: 'approved', priority: 'high', metadata: { type: 'IND', number: 'IND-156892', phase: 'I' } },
      { title: 'BLA Supplement - RheumaRelief New Indication', description: 'Biologics License Application supplement for additional indication in psoriatic arthritis. Includes Phase III pivotal data and updated labeling.', status: 'in_progress', priority: 'high', metadata: { type: 'sBLA', indication: 'Psoriatic Arthritis' } },
      { title: 'Type II DMF Submission - API Manufacturing', description: 'Drug Master File submission for new API manufacturing site. Complete CMC package including process description, specifications, stability data, and facility information.', status: 'submitted', priority: 'medium', metadata: { type: 'DMF Type II', facility: 'Chennai Manufacturing Plant' } },
      { title: 'Annual Report - NDA-189234', description: 'FDA annual report for approved product. Includes distribution data, labeling changes, ongoing studies, nonclinical studies, and any changes to conditions in application.', status: 'completed', priority: 'medium', metadata: { type: 'Annual Report', nda: 'NDA-189234' } },
      { title: 'Prior Approval Supplement - Manufacturing Change', description: 'PAS for significant manufacturing process change including new equipment and modified process parameters. Requires FDA approval before implementation.', status: 'review', priority: 'high', metadata: { type: 'PAS', change: 'Manufacturing Process', supplement: 'S-015' } },
      { title: 'CBE-30 Supplement - Labeling Update', description: 'Changes Being Effected in 30 days supplement for safety labeling update. New warnings and precautions based on post-market surveillance data.', status: 'submitted', priority: 'high', metadata: { type: 'CBE-30', change: 'Safety Labeling' } },
      { title: 'EU MAA Submission - NeuroClear', description: 'Marketing Authorization Application for European Union via centralized procedure. CHMP scientific assessment expected Q2 2024. Rapporteur and co-rapporteur assigned.', status: 'in_progress', priority: 'critical', metadata: { type: 'MAA', region: 'EU', procedure: 'Centralized' } },
      { title: 'Pediatric Study Plan (PSP) - AllerFree', description: 'Agreed pediatric study plan submitted to FDA. Includes proposed pediatric studies, formulation development plan, and timeline for completion.', status: 'approved', priority: 'medium', metadata: { type: 'PSP', population: 'Pediatric 2-17yr' } },
      { title: 'Orphan Drug Designation Request', description: 'Application for orphan drug designation for rare metabolic disorder treatment. Disease prevalence documentation, scientific rationale, and manufacturing plan included.', status: 'submitted', priority: 'high', metadata: { type: 'Orphan Drug', disease: 'Niemann-Pick Type C', prevalence: '< 200,000' } },
      { title: 'Fast Track Designation Request - OncoBlock', description: 'Request for Fast Track designation for immunotherapy in advanced NSCLC. Addresses serious condition and potential to fill unmet medical need with preliminary clinical evidence.', status: 'approved', priority: 'critical', metadata: { type: 'Fast Track', indication: 'Advanced NSCLC' } },
      { title: 'PAI Readiness Package - Manufacturing Site', description: 'Pre-Approval Inspection readiness documentation package. Equipment qualification summaries, validation protocols, batch records, and SOPs compiled for inspector review.', status: 'in_progress', priority: 'critical', metadata: { type: 'PAI Readiness', site: 'Primary Manufacturing' } },
      { title: 'Post-Approval Change Report - Packaging', description: 'Supplement for primary packaging change from glass to COP vials. Includes container closure integrity testing, extractables/leachables data, and stability bridging study.', status: 'review', priority: 'medium', metadata: { type: 'Supplement', change: 'Primary Packaging' } },
      { title: 'Breakthrough Therapy Application - GeneTx', description: 'Breakthrough Therapy designation request for gene therapy in rare genetic disorder. Substantial clinical improvement over existing treatments demonstrated in Phase II data.', status: 'submitted', priority: 'critical', metadata: { type: 'Breakthrough Therapy', modality: 'Gene Therapy' } },
    ],
    quality_control: [
      { title: 'OOS Investigation - Batch BT-5544 Dissolution', description: 'Out-of-specification investigation for dissolution failure at 30-minute timepoint. Phase I lab investigation completed. Assignable cause identified: tablet hardness excursion during compression.', status: 'in_progress', priority: 'critical', metadata: { type: 'OOS', batch: 'BT-5544', test: 'Dissolution', phase: 'Phase II' } },
      { title: 'Change Control - CC-2024-089 Process Parameter', description: 'Change control for modification of granulation endpoint from power consumption to NIR moisture monitoring. Risk assessment, validation protocol, and training plan included.', status: 'review', priority: 'high', metadata: { cc_number: 'CC-2024-089', type: 'Process Change', risk_level: 'Medium' } },
      { title: 'CAPA-2024-023 - Recurring Label Defects', description: 'Corrective and preventive action for recurring label misalignment issues. Root cause: vision system calibration drift. Corrective action: PM frequency increase and backup verification.', status: 'in_progress', priority: 'high', metadata: { capa_number: 'CAPA-2024-023', category: 'Label Defects', root_cause: 'Equipment Calibration' } },
      { title: 'Deviation Report - DEV-2024-156', description: 'Process deviation during tablet coating. Inlet air temperature exceeded upper limit by 3°C for 12 minutes. Product impact assessment indicates no effect on critical quality attributes.', status: 'completed', priority: 'medium', metadata: { deviation: 'DEV-2024-156', type: 'Process', impact: 'No Product Impact' } },
      { title: 'Method Validation - Assay by HPLC v2.0', description: 'Full method validation per ICH Q2(R2) for updated HPLC assay method. Specificity, linearity (R² = 0.9999), accuracy (99.2-100.8%), precision (RSD 0.3%), and robustness demonstrated.', status: 'approved', priority: 'high', metadata: { type: 'Method Validation', method: 'HPLC Assay v2.0', guideline: 'ICH Q2(R2)' } },
      { title: 'Supplier Qualification Audit - ChemSource Ltd', description: 'On-site audit of API supplier for cGMP compliance. Audit score: 88/100. Two major and four minor observations. Supplier qualification conditional on corrective action completion.', status: 'review', priority: 'high', metadata: { supplier: 'ChemSource Ltd', score: 88, findings: { major: 2, minor: 4 } } },
      { title: 'Environmental Monitoring Trend Report - Q1', description: 'Quarterly trending of environmental monitoring data for all classified areas. Alert levels exceeded twice in Grade B corridor. Investigation initiated for increased viable counts.', status: 'completed', priority: 'medium', metadata: { period: 'Q1 2024', areas_monitored: 12, alerts: 2, actions: 0 } },
      { title: 'Equipment Qualification - IQ/OQ/PQ Fluid Bed Dryer', description: 'Complete qualification package for new Glatt GPCG-60 fluid bed dryer. Installation, operational, and performance qualification protocols executed. All acceptance criteria met.', status: 'approved', priority: 'high', metadata: { equipment: 'Glatt GPCG-60', type: 'IQ/OQ/PQ', status: 'Qualified' } },
      { title: 'Cleaning Validation - Multi-Product Equipment', description: 'Cleaning validation for shared tablet press following worst-case product (high potency compound). Swab and rinse sampling. All residues below 1/1000 of therapeutic dose and 10 ppm criteria.', status: 'completed', priority: 'high', metadata: { equipment: 'Fette P2090', method: 'TOST Approach', worst_case: 'Compound HP-12' } },
      { title: 'Product Complaint Investigation - PC-2024-445', description: 'Investigation of customer complaint regarding tablet appearance (brown spots). Analysis confirms identity as iron oxide from degraded equipment gasket. CAPA initiated for PM schedule revision.', status: 'in_progress', priority: 'high', metadata: { complaint: 'PC-2024-445', type: 'Appearance', product: 'MetaboFix 250mg' } },
      { title: 'Process Validation Stage 2 - Continued Verification', description: 'Ongoing process verification report for established commercial product. CPV data for 30 consecutive batches. Process capability indices Ppk > 1.33 for all critical quality attributes.', status: 'completed', priority: 'medium', metadata: { stage: 'Stage 2', batches: 30, min_ppk: 1.45 } },
      { title: 'Data Integrity Remediation - Lab Systems', description: 'Data integrity remediation project for laboratory electronic systems. Gap assessment, risk-based prioritization, and implementation plan for ALCOA+ compliance across LIMS and CDS.', status: 'in_progress', priority: 'critical', metadata: { systems: 'LIMS/CDS', framework: 'ALCOA+', gaps_identified: 15 } },
      { title: 'Annual Quality Management Review', description: 'Comprehensive quality management review covering KPIs, CAPA effectiveness, audit findings, product quality trends, supplier performance, and regulatory inspection outcomes for 2024.', status: 'review', priority: 'high', metadata: { year: 2024, kpis_reviewed: 24, capa_effectiveness: '92%' } },
      { title: 'Stability Chamber Qualification - Mapping Study', description: 'Temperature and humidity mapping study for new walk-in stability chamber. 15-point monitoring over 7 days loaded and unloaded. All points within ±2°C and ±5% RH of setpoint.', status: 'approved', priority: 'medium', metadata: { type: 'Chamber Mapping', points: 15, duration: '7 days' } },
      { title: 'Risk Assessment - FMEA for Capsule Filling', description: 'Failure Mode and Effects Analysis for high-speed capsule filling process. 23 potential failure modes identified. Three modes with RPN > 100 require risk mitigation actions.', status: 'completed', priority: 'high', metadata: { type: 'FMEA', failure_modes: 23, high_risk: 3 } },
    ],
    adverse_events: [
      { title: 'SAE Report - CardioGuard XR Subject CG-301-1042', description: 'Serious adverse event report: hospitalization for GI hemorrhage in 67-year-old male, Day 45 of treatment. Assessed as possibly related. Drug discontinued, subject recovering.', status: 'submitted', priority: 'critical', metadata: { type: 'SAE', subject: 'CG-301-1042', event: 'GI Hemorrhage', causality: 'Possibly Related', outcome: 'Recovering' } },
      { title: 'SUSAR Notification - NeuroClear Study NC-201', description: 'Suspected Unexpected Serious Adverse Reaction: severe hepatotoxicity not listed in IB. 54-year-old female, ALT 15x ULN at Week 8. Expedited reporting to FDA within 7 days per IND safety reporting.', status: 'submitted', priority: 'critical', metadata: { type: 'SUSAR', event: 'Hepatotoxicity', timeline: '7-day report', subject: 'NC-201-0334' } },
      { title: 'Periodic Safety Update Report (PSUR) - Q4', description: 'Quarterly PSUR for approved products. Aggregate safety data analysis covering 45,000 patient-years of exposure. Benefit-risk assessment remains favorable. Two new signals under evaluation.', status: 'review', priority: 'high', metadata: { type: 'PSUR', period: 'Q4 2024', exposure: '45,000 patient-years', signals: 2 } },
      { title: 'Signal Detection Report - DiabControl', description: 'Disproportionality analysis of post-market safety data. New signal detected for pancreatitis (PRR 2.8, IC 1.4). Recommended for further clinical evaluation and potential labeling update.', status: 'in_progress', priority: 'high', metadata: { type: 'Signal Detection', drug: 'DiabControl', signal: 'Pancreatitis', prr: 2.8 } },
      { title: 'DSUR Annual Report - IND-156892', description: 'Development Safety Update Report for investigational compound ARX-7. Summary of all AEs across ongoing trials. No new safety concerns identified. DSMB concurs with continued development.', status: 'completed', priority: 'high', metadata: { type: 'DSUR', ind: 'IND-156892', period: 'Annual 2024' } },
      { title: 'AE Aggregate Analysis - PainEase XR Post-Market', description: 'Aggregate analysis of 1,247 adverse event reports from post-market surveillance. Most common: nausea (23%), headache (18%), dizziness (12%). No unexpected patterns detected.', status: 'completed', priority: 'medium', metadata: { total_reports: 1247, drug: 'PainEase XR', source: 'Post-Market' } },
      { title: 'DSMB Safety Review - Interim Analysis #3', description: 'Data Safety Monitoring Board review of unblinded interim safety data. O\'Brien-Fleming boundary not crossed. Recommendation to continue trial without modification.', status: 'completed', priority: 'critical', metadata: { type: 'DSMB', analysis: 'Interim #3', recommendation: 'Continue' } },
      { title: 'CIOMS Form Submission - International SAE', description: 'Council for International Organizations of Medical Sciences form for SAE reported at EU clinical site. Anaphylactic reaction at first dose. Subject recovered after epinephrine administration.', status: 'submitted', priority: 'critical', metadata: { type: 'CIOMS', event: 'Anaphylaxis', region: 'EU', outcome: 'Recovered' } },
      { title: 'Pregnancy Exposure Report - RheumaRelief', description: 'Report of inadvertent pregnancy exposure during clinical trial. Drug discontinued at 6 weeks gestation. Follow-up through delivery and 12 months post-natal per protocol requirements.', status: 'in_progress', priority: 'high', metadata: { type: 'Pregnancy Exposure', gestational_age: '6 weeks', followup: '12 months post-natal' } },
      { title: 'Medication Error Report - Dosing Mix-up', description: 'Report of medication error at clinical site: wrong dose administered (200mg instead of 100mg). No adverse outcome. Root cause: similar packaging between dose strengths.', status: 'completed', priority: 'high', metadata: { type: 'Medication Error', error: 'Wrong Dose', outcome: 'No Adverse Effect' } },
      { title: 'Risk Management Plan Update - OncoBlock', description: 'Updated risk management plan incorporating new safety data from Phase IIb trial. Additional risk minimization measures proposed for immune-related adverse events.', status: 'review', priority: 'high', metadata: { type: 'RMP Update', drug: 'OncoBlock', new_risks: 'irAE Management' } },
      { title: 'Post-Market AE Trending Report - Monthly', description: 'Monthly trending of spontaneous adverse event reports. 156 reports received. Reporting rate stable at 2.1 per 10,000 prescriptions. No new clusters or signals detected.', status: 'completed', priority: 'medium', metadata: { reports: 156, rate: '2.1/10K Rx', period: 'Monthly' } },
      { title: 'IND Safety Report - 15-Day Alert', description: 'IND safety report for unexpected fatal SAE in related compound class. Cross-reference analysis with own compound data. No similar events in current program.', status: 'submitted', priority: 'critical', metadata: { type: 'IND Safety Report', timeline: '15-day', event: 'Fatal SAE (Related Class)' } },
      { title: 'Benefit-Risk Assessment Update - HepatoShield', description: 'Updated benefit-risk framework analysis incorporating new 2-year safety data. Structured assessment using FDA benefit-risk framework. Overall benefit-risk remains positive.', status: 'completed', priority: 'high', metadata: { type: 'Benefit-Risk', drug: 'HepatoShield', framework: 'FDA BRF', assessment: 'Positive' } },
      { title: 'Safety Database Reconciliation Report', description: 'Quarterly reconciliation of safety database (Argus) with clinical database and regulatory submissions. 99.7% concordance achieved. Three discrepancies identified and corrected.', status: 'approved', priority: 'medium', metadata: { type: 'Reconciliation', system: 'Argus Safety', concordance: '99.7%' } },
    ],
    manufacturing_records: [
      { title: 'Batch Record - MetaboFix 250mg Tablets Lot MF-2024-067', description: 'Complete batch manufacturing record for 500,000 tablet batch. Granulation, compression, coating, and packaging stages documented. All in-process controls within specification.', status: 'approved', priority: 'high', metadata: { lot: 'MF-2024-067', product: 'MetaboFix 250mg', batch_size: '500,000 tablets', yield: '98.2%' } },
      { title: 'Master Batch Record Review - PainEase XR 200mg', description: 'Periodic review and update of master batch record incorporating validated process changes. Updated granulation parameters, compression force ranges, and coating solution preparation.', status: 'review', priority: 'high', metadata: { product: 'PainEase XR 200mg', version: '4.0', changes: 3 } },
      { title: 'Campaign Manufacturing Summary - March 2024', description: 'Monthly manufacturing campaign summary. 12 batches produced across 3 products. Overall OEE 87.5%. Two deviations documented, no batch rejections.', status: 'completed', priority: 'medium', metadata: { month: 'March 2024', batches: 12, products: 3, oee: '87.5%' } },
      { title: 'Aseptic Fill Record - Injectable Batch IB-902', description: 'Aseptic manufacturing record for sterile injectable product. Media fill simulation current. Environmental monitoring within limits. 10,000 vials filled, 99.98% visual inspection pass rate.', status: 'approved', priority: 'critical', metadata: { lot: 'IB-902', type: 'Aseptic Fill', units: 10000, inspection_pass: '99.98%' } },
      { title: 'Scale-Up Batch Record - NeuroClear Phase III Supply', description: 'Technology transfer and scale-up batch record from pilot (10kg) to commercial scale (100kg). Process parameters adjusted per scale-up calculations. Three registration batches planned.', status: 'in_progress', priority: 'critical', metadata: { scale: '10kg to 100kg', product: 'NeuroClear', purpose: 'Phase III Supply' } },
      { title: 'Packaging Record - AllerFree Syrup 60mL Bottles', description: 'Primary and secondary packaging record for oral syrup. Bottle filling, capping torque verification, label application, and carton packaging. Reconciliation completed within limits.', status: 'approved', priority: 'medium', metadata: { product: 'AllerFree Syrup 60mL', units: 25000, reconciliation: 'Pass' } },
      { title: 'Continuous Process Verification Report - Lot CPV-22', description: 'In-line process monitoring data for continuous manufacturing run. NIR, particle size, and blend uniformity real-time data within control limits for entire 48-hour campaign.', status: 'completed', priority: 'high', metadata: { type: 'Continuous Manufacturing', duration: '48 hours', monitoring: 'PAT/NIR' } },
      { title: 'Rework/Reprocess Record - Batch BT-5544R', description: 'Approved rework procedure for batch failing dissolution specification. Reprocessing via re-granulation with additional disintegrant. Reworked batch meets all specifications.', status: 'approved', priority: 'high', metadata: { type: 'Rework', original_batch: 'BT-5544', reason: 'Dissolution Failure' } },
      { title: 'Raw Material Dispensing Record - Week 12', description: 'Weekly raw material dispensing log covering 8 product campaigns. Balance verification, material identity confirmation, and dispensing booth environmental monitoring documented.', status: 'completed', priority: 'medium', metadata: { period: 'Week 12', campaigns: 8, materials: 34 } },
      { title: 'Equipment Cleaning Record - Tablet Press P2090', description: 'Cleaning record following product changeover from high-potency to standard product. Validated cleaning procedure followed. Swab and rinse samples collected for analysis.', status: 'completed', priority: 'high', metadata: { equipment: 'Fette P2090', changeover: 'HP-12 to MetaboFix', method: 'Validated SOP-CL-045' } },
      { title: 'Lyophilization Cycle Record - BioProduct BP-34', description: 'Freeze-drying cycle record for biologic product. Shelf temperature, chamber pressure, and product temperature profiles documented. Cake appearance acceptable, residual moisture 0.8%.', status: 'approved', priority: 'critical', metadata: { product: 'BP-34', type: 'Lyophilization', moisture: '0.8%', cycle_time: '72 hours' } },
      { title: 'Serialization Record - Batch SR-2024-March', description: 'Drug supply chain serialization data per DSCSA requirements. Unique product identifiers assigned. Aggregation hierarchy from unit to case to pallet documented.', status: 'completed', priority: 'medium', metadata: { regulation: 'DSCSA', units_serialized: 120000, levels: 'Unit/Case/Pallet' } },
      { title: 'Process Validation Protocol - New Product Launch', description: 'Prospective process validation protocol for three consecutive PPQ batches. Sampling plan, acceptance criteria, and statistical analysis methods defined per FDA guidance.', status: 'review', priority: 'critical', metadata: { type: 'PPQ Protocol', batches: 3, product: 'CardioGuard XR' } },
      { title: 'Water System Monitoring - WFI Generation', description: 'Daily monitoring records for Water for Injection system. TOC < 100 ppb, conductivity < 0.3 μS/cm, endotoxin < 0.03 EU/mL. All points within action limits.', status: 'approved', priority: 'high', metadata: { system: 'WFI', parameters: 'TOC/Conductivity/Endotoxin', status: 'Within Limits' } },
      { title: 'Batch Disposition Review - Monthly Summary', description: 'Quality unit batch disposition summary for March 2024. 12 batches reviewed: 11 approved for release, 1 under investigation. Average disposition time 5.2 days.', status: 'completed', priority: 'high', metadata: { month: 'March 2024', approved: 11, pending: 1, avg_days: 5.2 } },
    ],
    clinical_protocols: [
      { title: 'Protocol CG-301 - CardioGuard XR Phase III', description: 'Pivotal Phase III study protocol: randomized, double-blind, placebo-controlled, event-driven trial. Primary composite endpoint of CV death, MI, and stroke. Planned enrollment 2,400 subjects.', status: 'approved', priority: 'critical', metadata: { protocol: 'CG-301', phase: 'III', design: 'RCT Double-Blind', endpoint: 'MACE' } },
      { title: 'Protocol Amendment #3 - NC-201 NeuroClear', description: 'Protocol amendment to modify inclusion criteria (expanded age range 50-85), add biomarker substudy, and revise interim analysis timing based on DSMB recommendation.', status: 'review', priority: 'high', metadata: { protocol: 'NC-201', amendment: 3, changes: 'Inclusion/Substudy/Interim' } },
      { title: 'Statistical Analysis Plan - CG-301', description: 'Comprehensive SAP for Phase III cardiovascular outcomes trial. Primary analysis: Cox proportional hazards model. Multiple testing strategy: hierarchical testing for primary and key secondaries.', status: 'approved', priority: 'high', metadata: { protocol: 'CG-301', analysis: 'Cox PH Model', multiplicity: 'Hierarchical' } },
      { title: 'Informed Consent Form - OncoBlock Phase IIb', description: 'IRB-approved informed consent document for immunotherapy trial. Covers study procedures, risks including immune-related AEs, alternatives, and genetic sample consent.', status: 'approved', priority: 'high', metadata: { protocol: 'OB-201', irb: 'Central IRB', version: '2.1' } },
      { title: 'Site Initiation Visit Report - Site 045', description: 'SIV report for new clinical trial site. Facility assessment, staff training completion, IP storage verification, and regulatory document collection confirmed.', status: 'completed', priority: 'medium', metadata: { site: '045', investigator: 'Dr. R. Patel', training: 'Complete' } },
      { title: 'Data Management Plan - DiabControl Extension', description: 'Data management plan for 5-year extension study. EDC system configuration, data validation rules, medical coding dictionaries, and database lock procedures defined.', status: 'approved', priority: 'medium', metadata: { study: 'DiabControl Ext', edc: 'Medidata Rave', coding: 'MedDRA 26.0' } },
      { title: 'Monitoring Plan - Risk-Based Approach', description: 'Central and on-site monitoring plan per ICH E6(R2). Risk indicators defined for data quality, protocol compliance, and patient safety. Remote monitoring procedures for source data verification.', status: 'approved', priority: 'high', metadata: { approach: 'Risk-Based', guideline: 'ICH E6(R2)', tools: 'Central Statistical Monitoring' } },
      { title: 'Protocol Feasibility Assessment - Phase I Oncology', description: 'Feasibility assessment for first-in-human oncology study. Site selection criteria, enrollment projections, competing studies analysis, and regulatory landscape review.', status: 'completed', priority: 'medium', metadata: { indication: 'Solid Tumors', target_sites: 8, enrollment_rate: '2-3/site/month' } },
      { title: 'DSMB Charter - Vaccine Trial FluShield', description: 'Data Safety Monitoring Board charter defining membership, responsibilities, meeting schedule, and statistical monitoring guidelines. Stopping rules per O\'Brien-Fleming boundaries.', status: 'approved', priority: 'high', metadata: { study: 'FluShield Phase III', members: 5, meetings: 'Quarterly + Interim' } },
      { title: 'Investigator Brochure - Compound ARX-7 v5', description: 'Updated IB incorporating 12-month repeat-dose toxicology data, Phase I PK results, and revised pharmacology section. Risk assessment updated for dose escalation guidance.', status: 'review', priority: 'high', metadata: { compound: 'ARX-7', version: 5, updates: 'Tox/PK/Pharm' } },
      { title: 'Clinical Supply Management Plan', description: 'IP supply chain management for global Phase III trial. Manufacturing schedule, packaging/labeling by country, distribution logistics, temperature monitoring, and expiry management.', status: 'approved', priority: 'high', metadata: { trial: 'CG-301', countries: 12, depots: 4, supply_chain: 'IRT-Managed' } },
      { title: 'Bioanalytical Method Validation Protocol', description: 'LC-MS/MS method validation protocol for PK sample analysis. Validation parameters per FDA BMV guidance: selectivity, LLOQ, calibration, accuracy, precision, dilution integrity, stability.', status: 'approved', priority: 'high', metadata: { method: 'LC-MS/MS', analyte: 'ARX-7 and metabolites', guideline: 'FDA BMV 2018' } },
      { title: 'eCRF Completion Guidelines', description: 'Detailed electronic case report form completion guidelines for site staff. Field-by-field instructions, query resolution procedures, and data entry timelines specified.', status: 'completed', priority: 'medium', metadata: { study: 'CG-301', pages: 145, training: 'Required' } },
      { title: 'Pharmacy Manual - Multi-Site Trial', description: 'Clinical trial pharmacy manual covering IP receipt, storage, dispensing, accountability, return/destruction, and unblinding procedures for emergency situations.', status: 'approved', priority: 'medium', metadata: { study: 'CG-301', dispensing: 'IRT-Based', storage: '15-25°C' } },
      { title: 'Protocol Deviation Management SOP', description: 'Standard operating procedure for identifying, classifying, reporting, and trending protocol deviations. Major vs minor classification criteria and corrective action requirements defined.', status: 'approved', priority: 'high', metadata: { sop: 'SOP-CL-012', version: '3.0', classification: 'Major/Minor' } },
    ],
    drug_safety: [
      { title: 'Periodic Benefit-Risk Evaluation Report (PBRER)', description: 'Comprehensive periodic benefit-risk evaluation for CardioGuard XR covering 3-year post-approval period. Cumulative safety data from 28,000 patient-years of exposure analyzed.', status: 'review', priority: 'critical', metadata: { drug: 'CardioGuard XR', period: '3 years', exposure: '28,000 patient-years' } },
      { title: 'Signal Validation Report - Hepatotoxicity', description: 'Detailed signal validation analysis for hepatotoxicity signal detected in disproportionality analysis. Case-by-case review of 23 reports. Confounding factors and alternative etiologies assessed.', status: 'in_progress', priority: 'critical', metadata: { signal: 'Hepatotoxicity', cases: 23, method: 'Case-by-Case Review' } },
      { title: 'Aggregate Safety Report - Quarterly', description: 'Quarterly aggregate analysis of all safety data across product portfolio. Line listings, summary tabulations, and narrative summaries for all serious and unexpected events.', status: 'completed', priority: 'high', metadata: { period: 'Q4 2024', products: 8, total_events: 2340 } },
      { title: 'Reference Safety Information Update', description: 'Company Core Data Sheet (CCDS) update incorporating new safety information. Updated sections: Warnings, Adverse Reactions, Drug Interactions based on post-market surveillance data.', status: 'review', priority: 'high', metadata: { document: 'CCDS', version: '12.0', sections_updated: 3 } },
      { title: 'Pharmacovigilance System Master File', description: 'PSMF describing the pharmacovigilance system for EU-authorized products. QPPV designation, safety database description, contractual arrangements, and quality system documented.', status: 'approved', priority: 'high', metadata: { type: 'PSMF', qppv: 'Dr. M. Schmidt', region: 'EU' } },
      { title: 'Safety Specification Update - RheumaRelief', description: 'Updated safety specification per ICH E2E. Important identified risks, potential risks, and missing information reassessed based on 5-year cumulative data. Pharmacovigilance plan revised.', status: 'in_progress', priority: 'high', metadata: { drug: 'RheumaRelief', guideline: 'ICH E2E', identified_risks: 8, potential_risks: 4 } },
      { title: 'Drug Interaction Safety Review', description: 'Comprehensive review of drug-drug interaction safety data. In vitro CYP inhibition/induction, clinical DDI studies, and post-market interaction reports analyzed. Labeling recommendations provided.', status: 'completed', priority: 'high', metadata: { drug: 'HepatoShield', interactions_reviewed: 45, clinically_significant: 3 } },
      { title: 'Overdose Case Analysis Report', description: 'Analysis of reported overdose cases from clinical trials and post-market. 8 intentional and 3 accidental overdoses. Maximum reported dose 10x therapeutic. No fatalities.', status: 'completed', priority: 'high', metadata: { total_cases: 11, intentional: 8, accidental: 3, max_dose: '10x' } },
      { title: 'Pediatric Safety Review - AllerFree', description: 'Integrated safety analysis of pediatric clinical data. Weight-based dosing safety profile consistent with adult data. Growth and development monitoring showed no concerns.', status: 'review', priority: 'high', metadata: { drug: 'AllerFree', population: 'Pediatric 2-17yr', subjects: 340 } },
      { title: 'Pregnancy Registry Annual Report', description: 'Annual report from voluntary pregnancy exposure registry. 89 prospective enrollments, 72 outcomes available. Malformation rate consistent with background population rate.', status: 'completed', priority: 'high', metadata: { enrollments: 89, outcomes: 72, malformation_rate: 'Background Rate' } },
      { title: 'Safety Communication - DHPC Draft', description: 'Draft Direct Healthcare Professional Communication regarding new contraindication. Review and approval needed before distribution to healthcare professionals.', status: 'draft', priority: 'critical', metadata: { type: 'DHPC', topic: 'New Contraindication', audience: 'HCPs' } },
      { title: 'Literature Safety Review - Monthly', description: 'Systematic literature review for safety-relevant publications. PubMed, Embase, and Cochrane databases searched. 12 relevant articles identified, 2 requiring assessment as ICSRs.', status: 'completed', priority: 'medium', metadata: { databases: 3, articles_reviewed: 245, relevant: 12, icsrs: 2 } },
      { title: 'Safety Database Audit Report', description: 'Internal audit of safety database (Argus) data quality and compliance. 500 random cases audited. Data entry accuracy 98.2%. Three systemic issues identified with corrective actions.', status: 'completed', priority: 'high', metadata: { cases_audited: 500, accuracy: '98.2%', findings: 3 } },
      { title: 'Risk Minimization Measures Effectiveness', description: 'Assessment of additional risk minimization measures effectiveness. Patient card awareness survey (n=500): 78% recall. Prescriber education program completion rate: 92%.', status: 'review', priority: 'high', metadata: { measures: 'Patient Card + HCP Education', patient_recall: '78%', hcp_completion: '92%' } },
      { title: 'Comparative Safety Analysis - Class Review', description: 'Cross-compound safety comparison within therapeutic class. Meta-analysis of cardiovascular safety data across 5 approved agents. Relative risk estimates and forest plots generated.', status: 'completed', priority: 'high', metadata: { type: 'Class Review', compounds: 5, method: 'Meta-Analysis' } },
    ],
    pharmacovigilance: [
      { title: 'PV Agreement - Contract Research Organization', description: 'Pharmacovigilance agreement with CRO defining safety data exchange responsibilities, timelines, reconciliation procedures, and escalation pathways for clinical trial safety reporting.', status: 'approved', priority: 'high', metadata: { partner: 'GlobalTrials CRO', type: 'PV Agreement', scope: 'Clinical Trials' } },
      { title: 'ICSR Processing Metrics - Monthly', description: 'Monthly metrics for Individual Case Safety Report processing. 342 ICSRs received, 98.5% processed within regulatory timelines. Average processing time 3.2 days. Backlog: 0.', status: 'completed', priority: 'medium', metadata: { icsrs: 342, compliance: '98.5%', avg_time: '3.2 days' } },
      { title: 'Medical Device Vigilance Report', description: 'Vigilance report for drug-device combination product. Two device malfunctions reported (autoinjector failure to fire). No patient harm. Root cause under investigation.', status: 'in_progress', priority: 'high', metadata: { device: 'AutoInject Pro', events: 2, harm: 'None' } },
      { title: 'Signal Management Committee Minutes', description: 'Minutes from quarterly signal management committee meeting. Three signals reviewed: 1 validated (hepatotoxicity), 1 refuted (cardiac), 1 ongoing evaluation (renal).', status: 'completed', priority: 'high', metadata: { signals_reviewed: 3, validated: 1, refuted: 1, ongoing: 1 } },
      { title: 'PV System Inspection Readiness', description: 'Readiness assessment for potential competent authority PV inspection. Mock inspection findings addressed. Document room organized. Staff interview preparation completed.', status: 'in_progress', priority: 'critical', metadata: { type: 'Inspection Readiness', mock_findings: 5, status: 'Remediation In Progress' } },
      { title: 'Consumer Report Processing SOP Update', description: 'Updated SOP for processing adverse event reports from consumers/patients. New digital reporting channels integrated. Triage criteria for medical assessment revised.', status: 'review', priority: 'medium', metadata: { sop: 'SOP-PV-003', version: '4.0', channels: 'Phone/Web/App' } },
      { title: 'Regulatory Intelligence Report - Safety', description: 'Monthly regulatory intelligence report covering global safety regulatory changes. New EMA guidance on signal management, FDA FAERS database updates, and PMDA reporting changes summarized.', status: 'completed', priority: 'medium', metadata: { regions: 'FDA/EMA/PMDA', updates: 8, impact_assessment: 'Completed' } },
      { title: 'Case Causality Assessment Training', description: 'Training records for PV team causality assessment methodology. WHO-UMC system and Naranjo algorithm training completed. Competency assessment pass rate 100%.', status: 'completed', priority: 'medium', metadata: { method: 'WHO-UMC/Naranjo', trainees: 15, pass_rate: '100%' } },
      { title: 'Partner Company Safety Data Exchange', description: 'Quarterly safety data exchange with co-marketing partner. Line listings of all ICSRs exchanged. Reconciliation completed with 100% concordance. Joint signal evaluation documented.', status: 'completed', priority: 'high', metadata: { partner: 'PharmaCo Inc', icsrs_exchanged: 89, concordance: '100%' } },
      { title: 'PV Quality Metrics Dashboard - Annual', description: 'Annual PV quality metrics review. Case processing timeliness: 98.5%, data accuracy: 97.8%, regulatory reporting compliance: 99.2%. Quality targets met across all KPIs.', status: 'approved', priority: 'high', metadata: { timeliness: '98.5%', accuracy: '97.8%', compliance: '99.2%' } },
      { title: 'Social Media Safety Monitoring Report', description: 'Report on adverse event detection from social media monitoring program. 45 potential AEs identified from monitored platforms. 12 confirmed as valid ICSRs after medical review.', status: 'completed', priority: 'medium', metadata: { platforms_monitored: 5, potential_aes: 45, confirmed_icsrs: 12 } },
      { title: 'Medication Error Prevention Program', description: 'Annual review of medication error prevention initiatives. Name differentiation analysis, package design evaluation, and prescribing error trend analysis. Two packaging changes recommended.', status: 'review', priority: 'high', metadata: { errors_analyzed: 67, recommendations: 2, type: 'Packaging Changes' } },
      { title: 'Patient Support Program Safety Reporting', description: 'Safety reporting procedures for patient support program. Adverse event and product complaint capture, documentation, and forwarding procedures to PV department defined.', status: 'approved', priority: 'medium', metadata: { program: 'PatientFirst', participants: 5600, aes_reported: 34 } },
      { title: 'Risk-Based PV Audit Plan - 2025', description: 'Risk-based pharmacovigilance audit plan for upcoming year. Six planned audits: 2 internal, 2 CRO, 1 MAH partner, 1 safety database. Audit schedule and scope defined.', status: 'approved', priority: 'high', metadata: { year: 2025, audits: 6, types: 'Internal/CRO/Partner/System' } },
      { title: 'Aggregate Report Submission Tracker', description: 'Tracking log for all periodic aggregate safety report submissions globally. PSUR/PBRER, DSUR, and PADER submission dates, regulatory authority, and compliance status documented.', status: 'completed', priority: 'high', metadata: { reports_due: 24, submitted_on_time: 23, compliance: '95.8%' } },
    ],
    medical_literature: [
      { title: 'Systematic Review - Oral Anticoagulant Efficacy', description: 'Systematic review and meta-analysis of novel oral anticoagulants for stroke prevention in atrial fibrillation. 15 RCTs included, 78,000 patients. Network meta-analysis with SUCRA rankings.', status: 'completed', priority: 'high', metadata: { type: 'Systematic Review', studies: 15, patients: 78000, method: 'Network Meta-Analysis' } },
      { title: 'Literature Search Strategy - Hepatotoxicity Signal', description: 'Comprehensive literature search strategy for hepatotoxicity signal investigation. PubMed, Embase, Cochrane, and grey literature searched. PRISMA flow diagram documented.', status: 'completed', priority: 'high', metadata: { databases: 4, hits: 1245, screened: 312, included: 28 } },
      { title: 'Publication Bias Assessment - Anti-TNF Agents', description: 'Assessment of publication bias in anti-TNF agent clinical trials using funnel plots and Egger\'s test. Moderate asymmetry detected suggesting possible publication bias in small studies.', status: 'completed', priority: 'medium', metadata: { agents: 5, studies_analyzed: 42, test: 'Egger\'s', result: 'Moderate Bias' } },
      { title: 'Competitive Intelligence Report - Diabetes Pipeline', description: 'Literature-based competitive intelligence report on Type 2 diabetes drug pipeline. 12 compounds in Phase II+, 3 potential first-in-class mechanisms identified.', status: 'completed', priority: 'high', metadata: { compounds: 12, phases: 'II-III', novel_mechanisms: 3 } },
      { title: 'Clinical Practice Guideline Review - Hypertension', description: 'Review of updated clinical practice guidelines for hypertension management. Comparison of ACC/AHA, ESC/ESH, and NICE guidelines. Implications for product positioning analyzed.', status: 'completed', priority: 'medium', metadata: { guidelines: 3, year: 2024, implications: 'Product Positioning' } },
      { title: 'Real-World Evidence Literature Review', description: 'Comprehensive review of real-world evidence publications for PainEase XR. 18 observational studies identified. Effectiveness and safety consistent with clinical trial data.', status: 'completed', priority: 'high', metadata: { drug: 'PainEase XR', studies: 18, type: 'Observational' } },
      { title: 'Biomarker Literature Review - FGFR2 Fusion', description: 'Targeted literature review on FGFR2 fusion as predictive biomarker in solid tumors. Prevalence data, detection methods, and clinical outcomes with FGFR inhibitors summarized.', status: 'completed', priority: 'high', metadata: { biomarker: 'FGFR2 Fusion', articles: 34, tumor_types: 8 } },
      { title: 'Pharmacoeconomic Literature Analysis', description: 'Review of health economic publications relevant to upcoming HTA submissions. Cost-effectiveness analyses, QALY estimates, and budget impact models from comparable products analyzed.', status: 'completed', priority: 'medium', metadata: { type: 'Pharmacoeconomic', analyses: 15, markets: 'US/EU5/Japan' } },
      { title: 'Safety Literature Review - Pregnancy', description: 'Comprehensive literature review of drug exposure during pregnancy for product class. Animal reproductive toxicology and human pregnancy registry data summarized.', status: 'review', priority: 'high', metadata: { topic: 'Pregnancy Safety', articles: 22, registries: 4 } },
      { title: 'Gene Therapy Literature Landscape', description: 'Literature landscape analysis for gene therapy in rare genetic disorders. Current approved products, pipeline, manufacturing challenges, and regulatory precedents reviewed.', status: 'completed', priority: 'high', metadata: { approved_products: 6, pipeline: 45, regulatory_insights: 12 } },
      { title: 'Drug Resistance Mechanisms Review', description: 'Literature review on resistance mechanisms to targeted therapies in oncology. Acquired resistance pathways, combination strategies, and next-generation compound approaches analyzed.', status: 'completed', priority: 'medium', metadata: { mechanisms: 8, combination_strategies: 15, articles: 56 } },
      { title: 'Patient-Reported Outcomes Literature', description: 'Review of PRO instrument validation literature for rheumatoid arthritis. HAQ-DI, DAS28, and patient global assessment psychometric properties and responsiveness evaluated.', status: 'completed', priority: 'medium', metadata: { instruments: 3, validation_studies: 18 } },
      { title: 'Immunogenicity Literature Assessment', description: 'Literature review on immunogenicity of biologic products. Anti-drug antibody assay methodologies, clinical impact of immunogenicity, and risk mitigation strategies summarized.', status: 'completed', priority: 'high', metadata: { biologics_reviewed: 12, assay_methods: 4, topic: 'Immunogenicity' } },
      { title: 'Regulatory Science Publications Digest', description: 'Monthly digest of regulatory science publications from FDA, EMA, and ICH. New guidances, reflection papers, and concept papers relevant to product portfolio summarized.', status: 'completed', priority: 'medium', metadata: { sources: 'FDA/EMA/ICH', publications: 15, month: 'March 2024' } },
      { title: 'AI in Drug Development Literature Review', description: 'Review of artificial intelligence applications in pharmaceutical development. Machine learning in drug discovery, clinical trial optimization, manufacturing PAT, and pharmacovigilance.', status: 'completed', priority: 'medium', metadata: { applications: 4, articles: 67, emerging_trends: 5 } },
    ],
    sops: [
      { title: 'SOP-QC-001 - Laboratory Testing Procedures', description: 'Standard operating procedure for routine laboratory testing including sample receipt, testing sequence, data recording, result review, and OOS handling. Covers HPLC, dissolution, and wet chemistry.', status: 'approved', priority: 'high', metadata: { sop_number: 'SOP-QC-001', version: '6.0', effective_date: '2024-01-15', review_date: '2026-01-15' } },
      { title: 'SOP-MFG-012 - Tablet Compression Operations', description: 'Detailed SOP for tablet compression including machine setup, die/punch installation, compression force adjustment, in-process weight/hardness/thickness checks, and yield reconciliation.', status: 'approved', priority: 'high', metadata: { sop_number: 'SOP-MFG-012', version: '4.2', equipment: 'Fette P2090/Korsch XL400' } },
      { title: 'SOP-QA-005 - Deviation Management', description: 'Procedure for identifying, documenting, investigating, and resolving manufacturing and laboratory deviations. Classification criteria, investigation methodology, and CAPA linkage defined.', status: 'approved', priority: 'critical', metadata: { sop_number: 'SOP-QA-005', version: '5.0', scope: 'Manufacturing/Laboratory' } },
      { title: 'SOP-PV-003 - Adverse Event Processing', description: 'SOP for receipt, triage, data entry, medical assessment, causality evaluation, and regulatory reporting of individual case safety reports from all sources.', status: 'review', priority: 'critical', metadata: { sop_number: 'SOP-PV-003', version: '4.0', regulatory: 'FDA/EMA/ICH E2B(R3)' } },
      { title: 'SOP-CL-015 - Clinical Data Management', description: 'SOP covering EDC system management, data entry standards, query management, medical coding, SAE reconciliation, and database lock procedures for clinical trials.', status: 'approved', priority: 'high', metadata: { sop_number: 'SOP-CL-015', version: '3.1', system: 'Medidata Rave' } },
      { title: 'SOP-RA-008 - Regulatory Submission Preparation', description: 'Procedure for preparation, review, and submission of regulatory documents. eCTD compilation, quality review checklist, and electronic gateway submission steps detailed.', status: 'approved', priority: 'high', metadata: { sop_number: 'SOP-RA-008', version: '3.0', format: 'eCTD' } },
      { title: 'SOP-IT-002 - Electronic Records Management', description: '21 CFR Part 11 compliant SOP for electronic records. System access controls, audit trail requirements, electronic signature procedures, and system validation requirements.', status: 'approved', priority: 'high', metadata: { sop_number: 'SOP-IT-002', version: '2.5', compliance: '21 CFR Part 11' } },
      { title: 'SOP-WH-004 - Material Receipt and Quarantine', description: 'Warehouse SOP for incoming material receipt, inspection, sampling, quarantine management, and release/rejection disposition. Temperature-sensitive material handling included.', status: 'approved', priority: 'medium', metadata: { sop_number: 'SOP-WH-004', version: '3.0', scope: 'Raw Materials/Packaging' } },
      { title: 'SOP-ENG-007 - Equipment Qualification', description: 'SOP for equipment qualification lifecycle: User Requirements, DQ, FAT/SAT, IQ, OQ, PQ. Change control triggers for requalification and periodic review requirements.', status: 'approved', priority: 'high', metadata: { sop_number: 'SOP-ENG-007', version: '4.0', scope: 'All GMP Equipment' } },
      { title: 'SOP-HS-003 - Environmental Health and Safety', description: 'EHS procedures for pharmaceutical manufacturing including chemical handling, PPE requirements, spill response, exposure monitoring, and waste disposal procedures.', status: 'approved', priority: 'high', metadata: { sop_number: 'SOP-HS-003', version: '5.0', regulations: 'OSHA/EPA' } },
      { title: 'SOP-QC-018 - Stability Study Management', description: 'SOP for stability study design, sample pull schedules, testing requirements, data trending, and out-of-trend investigation per ICH Q1A-Q1E guidelines.', status: 'approved', priority: 'high', metadata: { sop_number: 'SOP-QC-018', version: '3.5', guideline: 'ICH Q1A-Q1E' } },
      { title: 'SOP-MFG-025 - Aseptic Processing', description: 'Comprehensive SOP for aseptic manufacturing including gowning, environmental monitoring, aseptic technique, media fill simulation, and intervention management.', status: 'approved', priority: 'critical', metadata: { sop_number: 'SOP-MFG-025', version: '6.0', area: 'Grade A/B' } },
      { title: 'SOP-QA-010 - Annual Product Review', description: 'Procedure for conducting annual product quality reviews. Data collection, statistical trending, stability review, CAPA effectiveness, and management review report preparation.', status: 'approved', priority: 'high', metadata: { sop_number: 'SOP-QA-010', version: '3.0', frequency: 'Annual' } },
      { title: 'SOP-TR-001 - Training Management', description: 'SOP for GMP training program management. Training needs assessment, curriculum development, delivery methods, effectiveness evaluation, and training record maintenance.', status: 'approved', priority: 'high', metadata: { sop_number: 'SOP-TR-001', version: '4.0', scope: 'All GMP Personnel' } },
      { title: 'SOP-VAL-006 - Cleaning Validation', description: 'SOP for cleaning validation program including worst-case product selection, sampling methods (swab/rinse), acceptance criteria calculation, and revalidation triggers.', status: 'approved', priority: 'high', metadata: { sop_number: 'SOP-VAL-006', version: '3.2', method: 'TOST/MACO' } },
    ],
    audit_trail: [
      { title: 'Internal Audit Report - Manufacturing Site A', description: 'Comprehensive GMP audit of primary manufacturing facility. 47 audit points assessed. 2 major observations: equipment logbook gaps and incomplete cleaning records. 5 minor observations noted.', status: 'completed', priority: 'high', metadata: { site: 'Manufacturing Site A', points: 47, major: 2, minor: 5 } },
      { title: 'Supplier Audit - PackRight Packaging Co', description: 'On-site supplier audit of primary packaging material supplier. Audit score 91/100. One minor observation regarding incoming material testing frequency. Approved supplier status maintained.', status: 'completed', priority: 'medium', metadata: { supplier: 'PackRight Co', score: 91, observations: 1, status: 'Approved' } },
      { title: 'Data Integrity Audit - LIMS System', description: 'Focused data integrity audit of Laboratory Information Management System. Audit trail functionality, user access controls, backup procedures, and electronic signature compliance assessed.', status: 'completed', priority: 'critical', metadata: { system: 'LIMS', focus: 'Data Integrity', findings: 4, alcoa_compliance: '92%' } },
      { title: 'Clinical Trial Audit - Site 023', description: 'GCP audit of high-enrolling clinical trial site. Protocol compliance, informed consent processes, source data verification, and IP accountability assessed. One critical finding.', status: 'in_progress', priority: 'critical', metadata: { site: '023', type: 'GCP', trial: 'CG-301', critical_findings: 1 } },
      { title: 'Regulatory Inspection History Log', description: 'Comprehensive log of all regulatory inspections from FDA, EMA, MHRA, and other authorities. Inspection dates, scope, findings, responses, and closeout status tracked.', status: 'approved', priority: 'high', metadata: { period: '2020-2024', inspections: 12, agencies: 4 } },
      { title: 'Quality System Audit - Document Control', description: 'Internal audit of document control system. Version management, distribution control, obsolete document handling, and training linkage assessed. Three observations noted.', status: 'completed', priority: 'medium', metadata: { system: 'Document Control', areas: 8, observations: 3 } },
      { title: 'Vendor Qualification Audit Trail', description: 'Complete audit trail for vendor qualification decisions. Risk assessments, qualification audits, ongoing monitoring, and requalification schedules documented for 45 critical vendors.', status: 'approved', priority: 'high', metadata: { vendors: 45, risk_levels: 'High/Medium/Low', requalification: 'Risk-Based' } },
      { title: 'Batch Record Review Audit - Q1 2024', description: 'Audit of batch record review process timeliness and thoroughness. 36 batch records reviewed. Average review cycle 4.8 days. Three records with incomplete review documentation.', status: 'completed', priority: 'medium', metadata: { records_audited: 36, avg_cycle: '4.8 days', deficiencies: 3 } },
      { title: 'PV System Audit - Safety Database', description: 'Pharmacovigilance system audit focusing on safety database operations. Case entry accuracy, regulatory reporting timeliness, and quality control procedures assessed.', status: 'completed', priority: 'high', metadata: { system: 'Argus Safety', cases_reviewed: 100, compliance: '97.5%' } },
      { title: 'Environmental Monitoring Audit', description: 'Audit of environmental monitoring program for classified manufacturing areas. Sampling locations, frequencies, trending, and alert/action level responses reviewed.', status: 'completed', priority: 'high', metadata: { areas: 'Grade A/B/C/D', locations: 156, trends: 'Within Limits' } },
      { title: 'Computer System Validation Audit', description: 'Audit of CSV practices across GxP systems. Validation documentation, change control, periodic reviews, and data migration procedures assessed for 8 systems.', status: 'in_progress', priority: 'high', metadata: { systems: 8, framework: 'GAMP 5', findings: 'Pending' } },
      { title: 'Training Compliance Audit', description: 'Audit of GMP training compliance across all departments. Training completion rates, effectiveness assessments, and retraining triggers reviewed. Overall compliance 96.2%.', status: 'completed', priority: 'medium', metadata: { departments: 7, overall_compliance: '96.2%', gaps: 12 } },
      { title: 'Warehouse and Distribution Audit', description: 'Audit of warehouse operations including receiving, storage, picking, shipping, and temperature monitoring. GDP compliance and product segregation practices assessed.', status: 'completed', priority: 'medium', metadata: { type: 'GDP', areas: 'Receiving/Storage/Shipping', temperature_excursions: 0 } },
      { title: 'Mock Recall Exercise Report', description: 'Annual mock recall exercise results. Product traced from finished goods to raw materials in 3.5 hours. 99.8% lot accountability achieved. One gap in distribution record identified.', status: 'completed', priority: 'high', metadata: { type: 'Mock Recall', time: '3.5 hours', accountability: '99.8%' } },
      { title: 'Management Review Audit Trail', description: 'Documentation of annual management review meeting. Quality metrics, audit findings, CAPA status, regulatory changes, and resource needs presented to senior management.', status: 'approved', priority: 'high', metadata: { type: 'Management Review', attendees: 12, action_items: 8 } },
    ],
    supply_chain: [
      { title: 'API Supply Agreement - ChemSource Ltd India', description: 'Active pharmaceutical ingredient supply agreement renewal. 3-year contract covering supply volumes, quality requirements, regulatory support obligations, and change notification provisions.', status: 'approved', priority: 'high', metadata: { supplier: 'ChemSource Ltd', location: 'India', term: '3 years', api: 'API-2947' } },
      { title: 'Cold Chain Qualification - Distribution Route US-EU', description: 'Temperature-controlled distribution lane qualification for biologic product shipment. Summer and winter profiles validated. Thermal packaging qualified for 96-hour transit.', status: 'approved', priority: 'critical', metadata: { route: 'US to EU', product: 'RheumaRelief', transit: '96 hours', range: '2-8°C' } },
      { title: 'Supply Chain Risk Assessment - 2024', description: 'Annual supply chain risk assessment covering single-source dependencies, geopolitical risks, natural disaster exposure, and supplier financial viability. Risk mitigation plans for 5 high-risk items.', status: 'completed', priority: 'high', metadata: { suppliers_assessed: 67, high_risk: 5, single_source: 3 } },
      { title: 'Inventory Optimization Report - Q1', description: 'Quarterly inventory analysis and optimization recommendations. Safety stock recalculation based on updated demand forecasts. $2.3M inventory reduction opportunity identified.', status: 'completed', priority: 'medium', metadata: { period: 'Q1 2024', sku_count: 145, reduction_opportunity: '$2.3M' } },
      { title: 'Serialization Compliance - DSCSA Implementation', description: 'Drug Supply Chain Security Act compliance status update. Unit-level serialization operational for all products. Transaction data exchange testing with wholesale distributors 95% complete.', status: 'in_progress', priority: 'critical', metadata: { regulation: 'DSCSA', phase: 'Enhanced Requirements', compliance: '95%' } },
      { title: 'Second Source Qualification - Excipient HPMC', description: 'Qualification of secondary excipient supplier for HPMC. Equivalency testing, stability bridging study, and regulatory filing strategy documented. Expected qualification Q2 2024.', status: 'in_progress', priority: 'high', metadata: { material: 'HPMC K100M', current: 'Supplier A', second: 'Supplier B' } },
      { title: 'Logistics Provider Performance Review', description: 'Annual performance review of third-party logistics providers. On-time delivery 97.2%, temperature excursions 0.3%, damage rate 0.1%. Two providers on improvement plans.', status: 'completed', priority: 'medium', metadata: { providers: 4, otd: '97.2%', excursions: '0.3%' } },
      { title: 'Raw Material Demand Forecast - H2 2024', description: 'Six-month demand forecast for critical raw materials. Production plan alignment, lead time analysis, and purchase order scheduling. Three materials with extended lead times flagged.', status: 'approved', priority: 'high', metadata: { period: 'H2 2024', materials: 45, critical_lead_times: 3 } },
      { title: 'GDP Self-Inspection Report', description: 'Good Distribution Practice self-inspection covering premises, equipment, documentation, operations, complaints, and recalls. Two observations noted regarding temperature logger calibration.', status: 'completed', priority: 'medium', metadata: { type: 'GDP Self-Inspection', areas: 6, observations: 2 } },
      { title: 'Clinical Trial Supply Chain Plan', description: 'Supply chain plan for global Phase III clinical trial supply. Depot strategy, country-specific requirements, IRT configuration, and resupply trigger points defined.', status: 'approved', priority: 'critical', metadata: { trial: 'CG-301', depots: 4, countries: 12, subjects: 2400 } },
      { title: 'Packaging Component Supply Review', description: 'Review of packaging component supply chain for all marketed products. Primary and secondary packaging material availability, dual sourcing status, and safety stock levels assessed.', status: 'completed', priority: 'medium', metadata: { components: 89, dual_sourced: '67%', at_risk: 5 } },
      { title: 'Import/Export License Management', description: 'Tracking of import/export licenses, permits, and certificates required for international pharmaceutical distribution. Renewal schedules, compliance status, and upcoming deadlines.', status: 'approved', priority: 'high', metadata: { licenses: 34, countries: 18, upcoming_renewals: 6 } },
      { title: 'Business Continuity Plan - Supply Chain', description: 'Supply chain business continuity plan covering pandemic, natural disaster, supplier failure, and transportation disruption scenarios. Response playbooks and communication trees defined.', status: 'approved', priority: 'critical', metadata: { scenarios: 4, playbooks: 8, last_drill: 'Q4 2023' } },
      { title: 'Contract Manufacturing Agreement - BioPharma GmbH', description: 'CMO agreement for biological product manufacturing. Technical transfer plan, quality agreement, regulatory filing support, and minimum batch commitments defined.', status: 'review', priority: 'high', metadata: { cmo: 'BioPharma GmbH', location: 'Germany', product: 'RheumaRelief' } },
      { title: 'Sustainability Report - Supply Chain', description: 'Annual supply chain sustainability metrics. Carbon footprint reduction 12% YoY, green chemistry initiatives in API synthesis, recyclable packaging adoption at 78%.', status: 'completed', priority: 'medium', metadata: { co2_reduction: '12%', green_chemistry: 'Adopted', recyclable_packaging: '78%' } },
    ],
    patent_documents: [
      { title: 'Patent Portfolio Review - CardioGuard XR', description: 'Comprehensive patent portfolio review for lead product. Composition of matter patent (expires 2031), method of use (2033), formulation (2035), and polymorph patents analyzed.', status: 'completed', priority: 'critical', metadata: { product: 'CardioGuard XR', patents: 4, earliest_expiry: 2031 } },
      { title: 'Freedom to Operate Analysis - ARX-7', description: 'FTO analysis for new compound ARX-7. Patent landscape search covering structural analogs, target biology, and manufacturing processes. Two potential blocking patents identified for design-around.', status: 'in_progress', priority: 'critical', metadata: { compound: 'ARX-7', blocking_patents: 2, jurisdictions: 'US/EU/JP' } },
      { title: 'Patent Application - Novel Crystal Form', description: 'Provisional patent application for newly discovered polymorph of NeuroClear. Characterization data, stability advantage, and manufacturing process for crystalline Form III.', status: 'submitted', priority: 'high', metadata: { type: 'Provisional', compound: 'NeuroClear', form: 'Polymorph III' } },
      { title: 'Paragraph IV Certification Response', description: 'Response to generic company\'s Paragraph IV certification challenging Orange Book listed patents. Infringement analysis, claim construction, and litigation strategy documented.', status: 'in_progress', priority: 'critical', metadata: { type: 'Paragraph IV', product: 'PainEase XR', challenger: 'GenericPharm Inc' } },
      { title: 'Patent Term Extension Application', description: 'PTE application for composition of matter patent based on regulatory review period. Calculation of eligible extension: 892 days regulatory review - 456 days due diligence = 436-day extension.', status: 'submitted', priority: 'high', metadata: { type: 'PTE', patent: 'US 10,XXX,XXX', extension: '436 days' } },
      { title: 'Trade Secret Assessment - Manufacturing Process', description: 'Assessment of proprietary manufacturing processes suitable for trade secret protection rather than patent filing. Covers continuous manufacturing know-how and PAT implementation.', status: 'completed', priority: 'high', metadata: { type: 'Trade Secret', processes: 3, protection: 'Non-Patent' } },
      { title: 'IP Due Diligence - Acquisition Target', description: 'Intellectual property due diligence report for potential acquisition. Patent portfolio strength, freedom to operate, pending litigation, and IP valuation assessed.', status: 'completed', priority: 'critical', metadata: { target: 'BioVenture Inc', patents_reviewed: 23, value_estimate: '$45M' } },
      { title: 'Patent Prosecution Status Report - Q1 2024', description: 'Quarterly status update on all pending patent applications. 12 applications in prosecution, 3 recently granted, 2 office action responses due. Budget tracking included.', status: 'completed', priority: 'high', metadata: { pending: 12, granted: 3, office_actions: 2 } },
      { title: 'Biosimilar Patent Strategy - RheumaRelief', description: 'Defensive patent strategy against potential biosimilar competition. Patent thicket analysis, additional method of treatment claims, and device patent opportunities identified.', status: 'in_progress', priority: 'critical', metadata: { product: 'RheumaRelief', strategy: 'Defensive', additional_filings: 3 } },
      { title: 'Licensing Agreement - University Research', description: 'Exclusive license agreement with State University for novel drug target patent. Terms: upfront $5M, milestones $50M total, royalty 4-6% on net sales.', status: 'approved', priority: 'high', metadata: { licensor: 'State University', type: 'Exclusive', upfront: '$5M', royalty: '4-6%' } },
      { title: 'Patent Landscape Analysis - FGFR Inhibitors', description: 'Comprehensive patent landscape for FGFR inhibitor class. 156 patent families identified. White space analysis for novel compound design and formulation approaches.', status: 'completed', priority: 'high', metadata: { class: 'FGFR Inhibitors', families: 156, white_space: 'Identified' } },
      { title: 'Data Exclusivity Tracker', description: 'Tracking of regulatory data exclusivity periods across global markets. NCE exclusivity, orphan exclusivity, and pediatric extensions documented. Key dates for all marketed products.', status: 'approved', priority: 'high', metadata: { products: 8, markets: 'US/EU/JP', exclusivity_types: 3 } },
      { title: 'IP Litigation Case File - Patent Infringement', description: 'Case file for patent infringement litigation against competitor. Claim charts, expert declarations, discovery documents, and Markman hearing preparations compiled.', status: 'in_progress', priority: 'critical', metadata: { case: 'PharmaDocs v. CompetitorX', court: 'District of Delaware', patent: 'US 10,XXX,YYY' } },
      { title: 'Supplementary Protection Certificate (SPC)', description: 'SPC applications filed in EU member states for pediatric extension. Additional 6-month protection based on completed pediatric investigation plan results.', status: 'submitted', priority: 'high', metadata: { type: 'SPC + Pediatric Extension', countries: 27, extension: '6 months' } },
      { title: 'Annual IP Strategy Review', description: 'Annual strategic review of intellectual property portfolio. Patent filing priorities, lifecycle management opportunities, and competitive threats assessed. Budget allocation for FY2025.', status: 'review', priority: 'high', metadata: { year: 2025, filings_planned: 8, budget: '$3.2M' } },
    ]
  };

  for (const [category, docs] of Object.entries(categories)) {
    for (const doc of docs) {
      await pool.query(
        `INSERT INTO documents (title, description, category, status, priority, metadata, created_by) VALUES ($1, $2, $3, $4, $5, $6, $7)`,
        [doc.title, doc.description, category, doc.status, doc.priority, JSON.stringify(doc.metadata), 'Dr. Sarah Johnson']
      );
    }
    console.log(`  ✓ Seeded ${docs.length} ${category} documents`);
  }

  console.log('\n✅ Database seeded successfully!');
  console.log(`   Total documents: ${Object.values(categories).reduce((a, b) => a + b.length, 0)}`);
  await pool.end();
}

seed().catch(err => {
  console.error('Seed error:', err);
  process.exit(1);
});
